[versions]
agp = "8.3.0-alpha16"
kotlin = "1.9.20"
ksp = "1.9.20-1.0.14"
roborazzi = "1.8.0-alpha-4"

core-ktx = "1.12.0"
lifecycle-runtime-ktx = "2.6.2"
activity-compose = "1.8.1"
compose-bom = "2023.10.01"

compose-compiler = "1.5.4"

room = "2.6.1"
destinations = "1.9.54"

glide = "4.14.2"
glide-compose = "1.0.0-beta01"

[libraries]
desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version = "2.0.4" }

core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version = "1.8.1" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
material3 = { group = "androidx.compose.material3", name = "material3", version = "1.2.0-alpha12" }

room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-ksp = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

destinations = { group = "io.github.raamcosta.compose-destinations", name = "animations-core", version.ref = "destinations" }
destinations-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "destinations" }

slf4j-android = { group = "org.slf4j", name = "slf4j-android", version = "1.7.36" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compose = { group = "com.github.bumptech.glide", name = "compose", version.ref = "glide-compose" }
glide-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }

color-picker = { group = "com.godaddy.android.colorpicker", name = "compose-color-picker", version = "0.7.0" }

# Testing
robolectric = { group = "org.robolectric", name = "robolectric", version = "4.11.1" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { group = "io.github.takahirom.roborazzi", name = "roborazzi-compose", version.ref = "roborazzi" }
junit = { group = "androidx.test.ext", name = "junit-ktx", version = "1.1.5" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-compiler" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose-compiler" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }